FIND_PATH(CL_DIR core.h
      ${CMAKE_SOURCE_DIR}/Include/ClanLib/
    )

FIND_LIBRARY(CL_CORE_LIBRARY_DEBUG
  NAMES clanCore-static-mt-debug
  PATHS ${CMAKE_SOURCE_DIR}/Lib/Win32/
    )

FIND_LIBRARY(CL_CORE_LIBRARY_RELEASE
  NAMES clanCore-static-mt
  PATHS ${CMAKE_SOURCE_DIR}/Lib/Win32/
    )
	
FIND_LIBRARY(CL_DB_LIBRARY_DEBUG
  NAMES clanDatabase-static-mt-debug
  PATHS ${CMAKE_SOURCE_DIR}/Lib/Win32/
    )

FIND_LIBRARY(CL_DB_LIBRARY_RELEASE
  NAMES clanDatabase-static-mt
  PATHS ${CMAKE_SOURCE_DIR}/Lib/Win32/
    )

FIND_LIBRARY(CL_NET_LIBRARY_DEBUG
  NAMES clanNetwork-static-mt-debug
  PATHS ${CMAKE_SOURCE_DIR}/Lib/Win32/
    )

FIND_LIBRARY(CL_NET_LIBRARY_RELEASE
  NAMES clanNetwork-static-mt
  PATHS ${CMAKE_SOURCE_DIR}/Lib/Win32/
    )
	
FIND_LIBRARY(CL_SOUND_LIBRARY_DEBUG
  NAMES clanSound-static-mt-debug
  PATHS ${CMAKE_SOURCE_DIR}/Lib/Win32/
    )

FIND_LIBRARY(CL_SOUND_LIBRARY_RELEASE
  NAMES clanSound-static-mt
  PATHS ${CMAKE_SOURCE_DIR}/Lib/Win32/
    )
	
FIND_LIBRARY(CL_SQ_LIBRARY_DEBUG
  NAMES clanSqlite-static-mt-debug
  PATHS ${CMAKE_SOURCE_DIR}/Lib/Win32/
    )

FIND_LIBRARY(CL_SQ_LIBRARY_RELEASE
  NAMES clanSqlite-static-mt
  PATHS ${CMAKE_SOURCE_DIR}/Lib/Win32/
    )
	
FIND_LIBRARY(CL_VORBIS_LIBRARY_DEBUG
  NAMES clanVorbis-static-mt-debug
  PATHS ${CMAKE_SOURCE_DIR}/Lib/Win32/
    )

FIND_LIBRARY(CL_VORBIS_LIBRARY_RELEASE
  NAMES clanVorbis-static-mt
  PATHS ${CMAKE_SOURCE_DIR}/Lib/Win32/
    )